### ISSUE TITLE
看了你的文章就来你的github了，等了一上午，你这边终于ok了

### ISSUE THREAD

**Issue by ilanni2460** [FrankenFuncc/consul-registy-service#1]
看了你的文章就来你的github了，等了一上午，你这边终于ok了

这个具体是如何使用的，有没有相关的readme

**Comment by FrankenFuncc** [comment]
程序很简单，只需要配置好consul集群的信息与，被注册的node_exporter的信息即可，我已经在README.md提交了一份配置文件实例。^^
